version: "3.7"
services:
  myadmin:
    image: phpmyadmin
    networks:
      - backend
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 7999:80

  mongoer:
    image: mongo-express
    networks:
      - backend
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGOER_USER
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGOER_PASSWORD
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
    ports:
      - 8081:8081

  insight:
    image: redislabs/redisinsight
    networks:
      - backend
    ports:
      - 8088:8001
