version: "3.7"
services:
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - backend
    volumes:
      - pgadmin_data:/var/lib/pgadmin:rw
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    ports:
      - 127.0.0.1:$PGSQL_UI_PORT:80
    depends_on:
      - pgsql

  myadmin:
    image: phpmyadmin
    networks:
      - backend
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - 127.0.0.1:$MYSQL_UI_PORT:80
    depends_on:
      - mysql

  mongoer:
    image: mongo-express
    networks:
      - backend
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
    ports:
      - 127.0.0.1:$MONGO_UI_PORT:8081
    depends_on:
      - mongo

  insight:
    image: redislabs/redisinsight
    networks:
      - backend
    volumes:
      - insight_data:/db
    ports:
      - 127.0.0.1:$REDIS_UI_PORT:8001
    depends_on:
      - redis

  xhgui:
    image: xhgui/xhgui
    networks:
      - backend
    volumes:
      - $XHPROF_CONFIG:/var/www/xhgui/config/config.php:ro
      - $XHPROF_NGINX_CONFIG:/etc/nginx/conf.d/default.conf:ro
      - webroot_share:/run/nginx
    environment:
      - XHGUI_MONGO_HOSTNAME=mongo
      - XHGUI_MONGO_PORT=$MONGO_PORT
      - XHGUI_MONGO_DATABASE=xhprof
      - XHGUI_MONGO_USERNAME=$MONGO_USER
      - XHGUI_MONGO_PASSWORD=$MONGO_PASSWORD
    ports:
      - 127.0.0.1:$XHPROF_UI_PORT:80
    depends_on:
      - mongo
volumes:
  webroot_share:
  pgadmin_data:
  insight_data:
