version: "3.7"
services:
  nginx:
    image: nginx:alpine
    networks:
      - backend
    environment:
      - TZ=$TIME_ZONE
    ports:
      - "127.0.0.1:${NGINX_PORT}:80"
      - "127.0.0.1:${NGINX_OTHER_PORT}:9090"
#      - "443:443"
    depends_on:
      - php8
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $OTHER_PROJECT_DIR:/var/www/webroot:rw
      - $NGINX_CONFIG_FILE:/etc/nginx/nginx.conf
      - $NGINX_CONFIG_DIR:/etc/nginx/conf.d
      - $NGINX_SSL_DIR:/etc/nginx/ssl
      - $NGINX_LOG_DIR:/var/log/nginx
    privileged: true
    extra_hosts:
      - host.docker.intenal:$LOCAL_IP_ADDR
    restart: always

  elastic6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.13
    networks:
      - backend
    volumes:
      - $ES_DATA_DIR:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:${ES_PORT}:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - node.name=docker-node
      - xpack.security.enabled=true
      - xpack.security.audit.enabled=true
      - ELASTIC_PASSWORD=$ES_PASSWORD
    restart: always
    privileged: true

  pgsql:
    image: postgres:alpine
    networks:
      - backend
    environment:
      - TZ=$TIME_ZONE
      - POSTGRES_PASSWORD=$PGSQL_PASSWORD
    volumes:
      - pgsql_data:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:${PGSQL_PORT}:5432"
    privileged: true
    restart: always

  mysql:
    image: mysql:latest
    networks:
      - backend
    environment:
      - TZ=$TIME_ZONE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - "127.0.0.1:${MYSQL_PORT}:3306"
    volumes:
      - $MYSQL_DATA_DIR:/var/lib/mysql:rw
      - $MYSQL_CONFIG_FILE:/etc/mysql/conf.d/my.cnf:ro
    privileged: true
    restart: always

  mongo:
    image: mongo
    networks:
      - backend
    ports:
      - "127.0.0.1:${MONGO_PORT}:27017"
    environment:
      - TZ=$TIME_ZONE
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - mongo_data:/data/db:rw
      - mongo_config:/data/configdb:rw
    privileged: true
    restart: always

  redis:
    image: redis:alpine
    networks:
      - backend
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
    environment:
      - TZ=$TIME_ZONE
    command: redis-server /etc/redis/redis.conf
    volumes:
      - $REDIS_CONFIG_FILE:/etc/redis/redis.conf
      - $REDIS_DATA_DIR:/data:rw
    privileged: true
    restart: always

  memcached:
    image: memcached:alpine
    networks:
      - backend
    ports:
      - "127.0.0.1:${MEMCACHED_PORT}:11211"
    environment:
      - TZ=$TIME_ZONE
    privileged: true
    restart: always

  rabbit:
    image: rabbitmq:management-alpine
    networks:
      - backend
    ports:
      - "127.0.0.1:${RABBIT_PORT}:5672"
      - "127.0.0.1:${RABBIT_UI_PORT}:15672"
    environment:
      - TZ=$TIME_ZONE
    volumes:
      - rabbit_data:/var/lib/rabbitmq:rw
      - $RABBIT_CONFIG_FILE:/etc/rabbitmq/rabbitmq.conf
    privileged: true
    restart: always

  zookeeper:
    image: zookeeper:latest
    networks:
      - backend
    ports:
      - "127.0.0.1:${ZOOKEEPER_PORT}:2181"
    environment:
      - TZ=$TIME_ZONE
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
      - $ZOOKEEPER_LOG_DIR:/logs
    privileged: true
    restart: always

  kafka:
    image: bitnami/kafka:latest
    networks:
      - backend
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      - TZ=$TIME_ZONE
      - KAFKA_BROKER_ID=0
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:${KAFKA_PORT}
      - KAFKA_CFG_ZOOKEEPER_SESSION_TIMEOUT=6000
    volumes:
      - kafka_data:/bitnami
    depends_on:
      - zookeeper
    privileged: true
    restart: always
