version: "3.7"
services:
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    networks:
      - backend
    ports:
      - "127.0.0.1:8978:8978"
    volumes:
      - ./dbeaver/workspace:/opt/cloudbeaver/workspace
    restart: always
    privileged: true

  mongoer:
    image: mongo-express
    networks:
      - backend
    environment:
      - TZ=$TIME_ZONE
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
    ports:
      - "127.0.0.1:${MONGO_UI_PORT}:8081"
    depends_on:
      - mongo
    restart: always

  insight:
    image: redislabs/redisinsight
    networks:
      - backend
    volumes:
      - insight_data:/db
    ports:
      - "127.0.0.1:${REDIS_UI_PORT}:8001"
    environment:
      - TZ=$TIME_ZONE
    depends_on:
      - redis
    restart: always

  xhgui:
    image: treelink123/xhgui
    networks:
      - backend
    volumes:
      - ./xhgui/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./xhgui/php.ini:/etc/php7/php.ini:ro
      - xhgui_webroot_share:/var/www/xhgui:rw
      - nginx_run:/run/nginx:rw
    environment:
      - TZ=$TIME_ZONE
      - XHGUI_MONGO_HOSTNAME=mongo
      - XHGUI_MONGO_PORT=$MONGO_PORT
      - XHGUI_MONGO_DATABASE=xhprof
      - XHGUI_MONGO_USERNAME=$MONGO_USER
      - XHGUI_MONGO_PASSWORD=$MONGO_PASSWORD
    ports:
      - "127.0.0.1:${XHPROF_UI_PORT}:80"
    depends_on:
      - mongo
    restart: always

  kibana8:
    image: docker.elastic.co/kibana/kibana:8.11.3
    networks:
      - backend
    ports:
      - "127.0.0.1:${KIBANA_PORT}:5601"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - es8
    restart: always
    privileged: true

  kafkaui:
    image: provectuslabs/kafka-ui:latest
    networks:
      - backend
    ports:
      - "127.0.0.1:${KAFKA_UI_PORT}:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    restart: always
    privileged: true
