version: "3.7"
services:
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - backend
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    ports:
      - 127.0.0.1:8804:80
    depends_on:
      - pgsql

  myadmin:
    image: phpmyadmin
    networks:
      - backend
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - 127.0.0.1:8801:80
    depends_on:
      - mysql

  mongoer:
    image: mongo-express
    networks:
      - backend
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
    ports:
      - 127.0.0.1:8802:8081
    depends_on:
      - mongo

  insight:
    image: redislabs/redisinsight
    networks:
      - backend
    volumes:
      - insight_data:/db
    ports:
      - 127.0.0.1:8803:8001
    depends_on:
      - redis
volumes:
  insight_data:
