version: "3.7"
services:
  apache:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:7-apache
    networks:
      - backend
    ports:
      - 127.0.0.1:$APACHE_PORT:80
    volumes:
      - $APACHE_PROJECT_DIR:/var/www/webroot:rw
      - $NGINX_PROJECT_DIR:/var/www/html:rw
      - xhgui_webroot_share:/var/www/xhgui:ro
      - $APACHE_CONF_FILE:/etc/apache2/sites-available/000-default.conf:ro
      - $PHP7_APACHE_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true

  php7:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:7-fpm-alpine
    networks:
      - backend
    ports:
      - 9505:9505
    volumes:
      - $APACHE_PROJECT_DIR:/var/www/webroot:rw
      - $NGINX_PROJECT_DIR:/var/www/html:rw
      - xhgui_webroot_share:/var/www/xhgui:ro
      - $PHP7_FPM_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true
#    extra_hosts:
#      - trink.devp:$LOCAL_IP_ADDR

  php7sw:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:7-cli-alpine
    networks:
      - backend
    ports:
      - 9501-9503:9501-9503
      - 9504:9504/udp
    volumes:
      - $APACHE_PROJECT_DIR:/var/www/webroot:rw
      - $NGINX_PROJECT_DIR:/var/www/html:rw
      - $PHP7_CLI_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true
    stdin_open: true
    tty: true
