version: "3.7"
services:
  apache:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:8-apache
    networks:
      - backend
    ports:
      - 127.0.0.1:9002:80
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $APACHE_CONF_FILE:/etc/apache2/sites-available/000-default.conf
#      - $APACHE_PHP_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true

  php7:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:7-fpm-alpine
    networks:
      - backend
    ports:
      - 127.0.0.1:9001:80
      - 18081:18081
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
#      - $PHP7_INI_FILE:/usr/local/etc/php/php.ini:ro
      - $APACHE_CONF_FILE:/etc/apache2/sites-available/000-default.conf:ro
    privileged: true
#    extra_hosts:
#      - trink.test:$LOCAL_IP_ADDR

  php7sw:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:7-cli-alpine
    networks:
      - backend
    ports:
      - 9501:9501
      - 9502:9502/udp
      - 9503-9504:9503-9504
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
#      - $PHP7_SWOOLE_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true
    stdin_open: true
    tty: true
