version: "3.7"
services:
  redis_master:
    image: redis
    networks:
      backend:
        ipv4_address: 172.63.11.2
    command: redis-server /etc/redis/master.conf
    volumes:
      - $REDIS_MASTER_CONFIG_FILE:/etc/redis/master.conf:rw
    ports:
      - 6380:6379
    privileged: true

  redis_replica1:
    image: redis
    networks:
      backend:
        ipv4_address: 172.63.11.3
    command: redis-server /etc/redis/replica1.conf
    volumes:
      - $REDIS_REPLICA1_CONFIG_FILE:/etc/redis/replica1.conf:rw
      - $REDIS_REPLICA1_DATA_DIR:/data:rw
    ports:
      - 6381:6379
    privileged: true
  redis_replica2:
    image: redis
    networks:
      backend:
        ipv4_address: 172.63.11.4
    command: redis-server /etc/redis/replica2.conf
    depends_on:
      - redis_master
    volumes:
      - $REDIS_REPLICA2_CONFIG_FILE:/etc/redis/replica2.conf:rw
      - $REDIS_REPLICA2_DATA_DIR:/data:rw
    ports:
      - 6382:6379
    privileged: true

  redis_sentinel1:
    image: redis
    networks:
      backend:
        ipv4_address: 172.63.11.21
    command: redis-sentinel /etc/redis/sentinel1.conf
    depends_on:
      - redis_master
      - redis_replica1
      - redis_replica2
    ports:
      - 26380:26379
    volumes:
      - $REDIS_SENTINEL1_CONFIG_FILE:/etc/redis/sentinel1.conf:rw
    privileged: true
  redis_sentinel2:
    image: redis
    networks:
      backend:
        ipv4_address: 172.63.11.22
    command: redis-sentinel /etc/redis/sentinel2.conf
    depends_on:
      - redis_master
      - redis_replica1
      - redis_replica2
    ports:
      - 26381:26379
    volumes:
      - $REDIS_SENTINEL2_CONFIG_FILE:/etc/redis/sentinel2.conf:rw
    privileged: true
  redis_sentinel3:
    image: redis
    networks:
      backend:
        ipv4_address: 172.63.11.23
    command: redis-sentinel /etc/redis/sentinel3.conf
    depends_on:
      - redis_master
      - redis_replica1
      - redis_replica2
    ports:
      - 26382:26379
    volumes:
      - $REDIS_SENTINEL3_CONFIG_FILE:/etc/redis/sentinel3.conf:rw
    privileged: true
