version: "3.7"
services:
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - backend
    volumes:
      - pgadmin_data:/var/lib/pgadmin:rw
    environment:
      - TZ=$TIME_ZONE
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    ports:
      - "127.0.0.1:${PGSQL_UI_PORT}:80"
    depends_on:
      - pgsql
    restart: always

  myadmin:
    image: phpmyadmin
    networks:
      - backend
    environment:
      - TZ=$TIME_ZONE
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - "127.0.0.1:${MYSQL_UI_PORT}:80"
    depends_on:
      - mysql
    restart: always

  mongoer:
    image: mongo-express
    networks:
      - backend
    environment:
      - TZ=$TIME_ZONE
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
    ports:
      - "127.0.0.1:${MONGO_UI_PORT}:8081"
    depends_on:
      - mongo
    restart: always

  insight:
    image: redislabs/redisinsight
    networks:
      - backend
    volumes:
      - insight_data:/db
    ports:
      - "127.0.0.1:${REDIS_UI_PORT}:8001"
    environment:
      - TZ=$TIME_ZONE
    depends_on:
      - redis
    restart: always

  xhgui:
    image: treelink123/xhgui
    networks:
      - backend
    volumes:
      - $XHGUI_NGINX_CONFIG:/etc/nginx/conf.d/default.conf:ro
      - $XHGUI_PHP_INI:/etc/php7/php.ini:ro
      - xhgui_webroot_share:/var/www/xhgui:rw
      - nginx_run:/run/nginx:rw
    environment:
      - TZ=$TIME_ZONE
      - XHGUI_MONGO_HOSTNAME=mongo
      - XHGUI_MONGO_PORT=$MONGO_PORT
      - XHGUI_MONGO_DATABASE=xhprof
      - XHGUI_MONGO_USERNAME=$MONGO_USER
      - XHGUI_MONGO_PASSWORD=$MONGO_PASSWORD
    ports:
      - "127.0.0.1:${XHPROF_UI_PORT}:80"
    depends_on:
      - mongo
    restart: always

  kibana6:
    image: docker.elastic.co/kibana/kibana:6.8.13
    volumes:
      - $KIBANA_CONFIG_FILE:/usr/share/kibana/config/kibana.yml
    ports:
      - "127.0.0.1:${KIBANA_PORT}:5601"
    networks:
      - backend
    environment:
      - ELASTICSEARCH_USERNAME=$ES_USERNAME
      - ELASTICSEARCH_PASSWORD=$ES_PASSWORD
    depends_on:
      - elastic6
    restart: always
    privileged: true

  kafkaui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "127.0.0.1:${KAFKA_UI_PORT}:8080"
    networks:
      - backend
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    restart: always
    privileged: true
