version: "3.7"
services:
  php8:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:8-fpm
    networks:
      - backend
    ports:
      - "9505:9505"
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $OTHER_PROJECT_DIR:/var/www/webroot:rw
      - xhgui_webroot_share:/var/www/xhgui:rw
      - $PHP8_FPM_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true
    restart: always

  php8sw:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:8-cli
    networks:
      - backend
    environment:
      - PHP_IDE_CONFIG=serverName=localhost # yasd 需要
    ports:
      - "9501-9503:9501-9503"
      - "9504:9504/udp"
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $OTHER_PROJECT_DIR:/var/www/webroot:rw
      - $PHP8_CLI_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true
    stdin_open: true
    tty: true
    restart: always
