version: "3.7"
services:
  php7:
    image: treelink123/php:7-fpm
    networks:
      - backend
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $OTHER_PROJECT_DIR:/var/www/webroot:rw
      - xhgui_webroot_share:/var/www/xhgui:rw
      - ./php/php7.fpm.ini:/usr/local/etc/php/php.ini:ro
    privileged: true
    restart: always

  php8:
    image: treelink123/php:8-fpm
    networks:
      - backend
    ports:
      - "9505:9505"
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $OTHER_PROJECT_DIR:/var/www/webroot:rw
      - xhgui_webroot_share:/var/www/xhgui:rw
      - ./php/php8.fpm.ini:/usr/local/etc/php/php.ini:ro
    privileged: true
    restart: always

  php8sw:
    image: treelink123/php:8-cli
    networks:
      - backend
    environment:
      - PHP_IDE_CONFIG=serverName=localhost # yasd 需要
    ports:
      - "9501-9503:9501-9503"
      - "9504:9504/udp"
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $OTHER_PROJECT_DIR:/var/www/webroot:rw
      - ./php/php8.cli.ini:/usr/local/etc/php/php.ini:ro
    privileged: true
    stdin_open: true
    tty: true
    restart: always
