version: "3.7"
services:
  redis_cluster1:
    image: redis
    networks:
      backend:
        ipv4_address: 172.63.11.101
    command: redis-server /etc/redis/redis.conf
    volumes:
      - $REDIS_CLUSTER_NODE1_CONFIG_FILE:/etc/redis/redis.conf:rw
      - $REDIS_CLUSTER_NODE1_DATA_DIR:/data:rw
    ports:
      - 7001:6379
    privileged: true
  redis_cluster2:
    image: redis
    networks:
      backend:
        ipv4_address: 172.63.11.102
    command: redis-server /etc/redis/redis.conf
    volumes:
      - $REDIS_CLUSTER_NODE2_CONFIG_FILE:/etc/redis/redis.conf:rw
      - $REDIS_CLUSTER_NODE2_DATA_DIR:/data:rw
    ports:
      - 7002:6379
    privileged: true
  redis_cluster3:
    image: redis
    networks:
      backend:
        ipv4_address: 172.63.11.103
    command: redis-server /etc/redis/redis.conf
    volumes:
      - $REDIS_CLUSTER_NODE3_CONFIG_FILE:/etc/redis/redis.conf:rw
      - $REDIS_CLUSTER_NODE3_DATA_DIR:/data:rw
    ports:
      - 7003:6379
    privileged: true
  redis_cluster4:
    image: redis
    networks:
      backend:
        ipv4_address: 172.63.11.104
    command: redis-server /etc/redis/redis.conf
    volumes:
      - $REDIS_CLUSTER_NODE4_CONFIG_FILE:/etc/redis/redis.conf:rw
      - $REDIS_CLUSTER_NODE4_DATA_DIR:/data:rw
    ports:
      - 7004:6379
    privileged: true
  redis_cluster5:
    image: redis
    networks:
      backend:
        ipv4_address: 172.63.11.105
    command: redis-server /etc/redis/redis.conf
    volumes:
      - $REDIS_CLUSTER_NODE5_CONFIG_FILE:/etc/redis/redis.conf:rw
      - $REDIS_CLUSTER_NODE5_DATA_DIR:/data:rw
    ports:
      - 7005:6379
    privileged: true
  redis_cluster6:
    image: redis
    networks:
      backend:
        ipv4_address: 172.63.11.106
    command: redis-server /etc/redis/redis.conf
    volumes:
      - $REDIS_CLUSTER_NODE6_CONFIG_FILE:/etc/redis/redis.conf:rw
      - $REDIS_CLUSTER_NODE6_DATA_DIR:/data:rw
    ports:
      - 7006:6379
    privileged: true
  redis_cluster7:
    image: redis
    networks:
      backend:
        ipv4_address: 172.63.11.107
    command: redis-server /etc/redis/redis.conf
    volumes:
      - $REDIS_CLUSTER_NODE7_CONFIG_FILE:/etc/redis/redis.conf:rw
      - $REDIS_CLUSTER_NODE7_DATA_DIR:/data:rw
    ports:
      - 7007:6379
    privileged: true
  redis_cluster8:
    image: redis
    networks:
      backend:
        ipv4_address: 172.63.11.108
    command: redis-server /etc/redis/redis.conf
    volumes:
      - $REDIS_CLUSTER_NODE8_CONFIG_FILE:/etc/redis/redis.conf:rw
      - $REDIS_CLUSTER_NODE8_DATA_DIR:/data:rw
    ports:
      - 7008:6379
    privileged: true
