version: "3.7"
services:
  nginx:
    image: nginx
    networks:
      - backend
    ports:
      - 127.0.0.1:80:80
      - 443:443
    depends_on:
      - phpx7
      - phpsw7
      - phpx8
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $NGINX_CONFIG_FILE:/etc/nginx/nginx.conf
      - $NGINX_CONFIG_DIR:/etc/nginx/conf.d
      - $NGINX_SSL_DIR:/etc/nginx/ssl
      - $NGINX_LOG_DIR:/var/log/nginx
    privileged: true

  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/mysql:mysql-sysbench
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql_data:/var/lib/mysql:rw
#      - $MYSQL_CONFIG_FILE:/etc/mysql/my.cnf
    privileged: true

  pgsql:
    image: postgres
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=$PGSQL_PASSWORD
    volumes:
      - pgsql_data:/var/lib/postgresql/data:rw
    ports:
      - 127.0.0.1:5432:5432
    privileged: true

  mongo:
    image: mongo
    networks:
      - backend
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - mongo_data:/data/db:rw
    privileged: true

  redis:
    image: redis
    networks:
      - backend
    ports:
      - 127.0.0.1:6379:6379
    command: redis-server /etc/redis/redis.conf
    volumes:
      - $REDIS_CONFIG_FILE:/etc/redis/redis.conf
      - redis_data:/data:rw
    privileged: true

  memcached:
    image: memcached
    networks:
      - backend
    ports:
      - 127.0.0.1:11211:11211
    privileged: true

  rabbit:
    image: rabbitmq:management
    networks:
      - backend
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
    volumes:
      - rabbit_data:/var/lib/rabbitmq/mnesia:rw
      - $RABBIT_CONFIG_FILE:/etc/rabbitmq/rabbitmq.conf
    privileged: true
networks:
  backend:
volumes:
  mysql_data:
  mongo_data:
  pgsql_data:
  redis_data:
  rabbit_data:
  insight_data:
