version: "3.7"
services:
  php7:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:7.4-apache
    networks:
      - backend
    expose:
      - 9000
    ports:
      - 127.0.0.1:9001:80
      - 18081:18081
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP7_XDEBUG_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true
#    extra_hosts:
#      - trink.test:$LOCAL_IP_ADDR

  php7sw:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:7.4-swoole
    networks:
      - backend
    expose:
      - 9000
    ports:
      - 9501:9501
      - 9502:9502/udp
      - 9503-9504:9503-9504
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP7_SWOOLE_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true
    stdin_open: true
    tty: true

  php8:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:8.0-apache
    networks:
      - backend
    expose:
      - 9000
    ports:
      - 127.0.0.1:9002:80
      - 18082:18082
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP8_XDEBUG_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true

  php8sw:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:8.0-swoole
    networks:
      - backend
    expose:
      - 9000
    ports:
      - 18001:9501
      - 18002:9502/udp
      - 18003-18004:9503-9504
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP8_SWOOLE_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true
    stdin_open: true
    tty: true
