version: "3.7"
services:
  nginx:
    image: nginx:alpine
    networks:
      - backend
    ports:
      - 127.0.0.1:$NGINX_PORT:80
#      - 443:443
    depends_on:
      - php7
      - php7sw
    volumes:
      - $APACHE_PROJECT_DIR:/var/www/webroot:rw
      - $NGINX_PROJECT_DIR:/var/www/html:rw
      - xhgui_webroot_share:/var/www/xhgui:ro
      - $NGINX_CONFIG_FILE:/etc/nginx/nginx.conf
      - $NGINX_CONFIG_DIR:/etc/nginx/conf.d
      - $NGINX_SSL_DIR:/etc/nginx/ssl
      - $NGINX_LOG_DIR:/var/log/nginx
    privileged: true

  pgsql:
    image: postgres:alpine
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=$PGSQL_PASSWORD
    volumes:
      - pgsql_data:/var/lib/postgresql/data:rw
    ports:
      - 127.0.0.1:$PGSQL_PORT:5432
    privileged: true

  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/mysql:sysbench
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - 127.0.0.1:$MYSQL_PORT:3306
    volumes:
      - $MYSQL_DATA_DIR:/var/lib/mysql:rw
      - $MYSQL_CONFIG_FILE:/etc/mysql/conf.d/my.cnf:ro
    privileged: true

  mongo:
    image: mongo
    networks:
      - backend
    ports:
      - 127.0.0.1:$MONGO_PORT:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - mongo_data:/data/db:rw
      - mongo_config:/data/configdb:rw
    privileged: true

  redis:
    image: redis:alpine
    networks:
      - backend
    ports:
      - 127.0.0.1:$REDIS_PORT:6379
    command: redis-server /etc/redis/redis.conf
    volumes:
      - $REDIS_CONFIG_FILE:/etc/redis/redis.conf
      - redis_data:/data:rw
    privileged: true

  memcached:
    image: memcached:alpine
    networks:
      - backend
    ports:
      - 127.0.0.1:$MEMCACHED_PORT:11211
    privileged: true

  rabbit:
    image: rabbitmq:management-alpine
    networks:
      - backend
    ports:
      - 127.0.0.1:$RABBIT_PORT:5672
      - 127.0.0.1:$RABBIT_UI_PORT:15672
    volumes:
      - rabbit_data:/var/lib/rabbitmq:rw
      - $RABBIT_CONFIG_FILE:/etc/rabbitmq/rabbitmq.conf
    privileged: true
volumes:
  pgsql_data:
  mongo_config:
  mongo_data:
  redis_data:
  rabbit_data:
