version: "3.7"
services:
  memcached1:
    image: memcached
    networks:
      - backend
    ports:
      - "11212:11211"
    privileged: true

  memcached2:
    image: memcached
    networks:
      - backend
    ports:
      - "11213:11211"
    privileged: true

  memcached3:
    image: memcached
    networks:
      - backend
    ports:
      - "11214:11211"
    privileged: true

  memcached4:
    image: memcached
    networks:
      - backend
    ports:
      - "11215:11211"
    privileged: true