version: "3.7"
services:
  redis1_master:
    image: redis
    networks:
      db_redis:
        ipv4_address: 172.65.0.2
    command: redis-server /etc/redis/master.conf
    volumes:
      - $REDIS1_MASTER_CONFIG_FILE:/etc/redis/master.conf:rw
    ports:
      - 6380:6379
    privileged: true

  redis1_replica1:
    image: redis
    networks:
      db_redis:
        ipv4_address: 172.65.0.3
    command: redis-server /etc/redis/replica1.conf
    volumes:
      - $REDIS1_REPLICA1_CONFIG_FILE:/etc/redis/replica1.conf:rw
      - $REDIS1_REPLICA1_DATA_DIR:/data:rw
    ports:
      - 6381:6379
    privileged: true
  redis1_replica2:
    image: redis
    networks:
      db_redis:
        ipv4_address: 172.65.0.4
    command: redis-server /etc/redis/replica2.conf
    depends_on:
      - redis1_master
    volumes:
      - $REDIS1_REPLICA2_CONFIG_FILE:/etc/redis/replica2.conf:rw
      - $REDIS1_REPLICA2_DATA_DIR:/data:rw
    ports:
      - 6382:6379
    privileged: true

  redis1_sentinel1:
    image: redis
    networks:
      db_redis:
        ipv4_address: 172.65.0.21
    command: redis-sentinel /etc/redis/sentinel1.conf
    depends_on:
      - redis1_master
      - redis1_replica1
      - redis1_replica2
    ports:
      - 26380:26379
    volumes:
      - $REDIS1_SENTINEL1_CONFIG_FILE:/etc/redis/sentinel1.conf:rw
    privileged: true
  redis1_sentinel2:
    image: redis
    networks:
      db_redis:
        ipv4_address: 172.65.0.22
    command: redis-sentinel /etc/redis/sentinel2.conf
    depends_on:
      - redis1_master
      - redis1_replica1
      - redis1_replica2
    ports:
      - 26381:26379
    volumes:
      - $REDIS1_SENTINEL2_CONFIG_FILE:/etc/redis/sentinel2.conf:rw
    privileged: true
  redis1_sentinel3:
    image: redis
    networks:
      db_redis:
        ipv4_address: 172.65.0.23
    command: redis-sentinel /etc/redis/sentinel3.conf
    depends_on:
      - redis1_master
      - redis1_replica1
      - redis1_replica2
    ports:
      - 26382:26379
    volumes:
      - $REDIS1_SENTINEL3_CONFIG_FILE:/etc/redis/sentinel3.conf:rw
    privileged: true
