version: "3.7"
services:
  phpx5:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php5-fpm-xdebug
    networks:
      - backend
    expose:
      - 9000
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP5_XDEBUG_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true

  phpx7:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php7-fpm-xdebug
    networks:
      - backend
    expose:
      - 9000
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP7_XDEBUG_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true

  phpsw7:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php7-fpm-swoole
    networks:
      - backend
    expose:
      - 9000
    ports:
      - 9502:9502/udp
      - 9501-9510:9501-9510
      - 18305-18310:18305-18310
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP7_SWOOLE_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true

  php8:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php8-fpm
    networks:
      - backend
    expose:
      - 9000
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP8_INI_FILE:/usr/local/etc/php/php.ini:ro
    extra_hosts:
      - trink.test:$LOCAL_IP_ADDR
    privileged: true
