version: "3.7"
services:
  redis1:
    image: redis
    networks:
      - backend
    ports:
      - "6380:6379"
    privileged: true

  redis2:
    image: redis
    networks:
      - backend
    ports:
      - "6381:6379"
    privileged: true

  redis3:
    image: redis
    networks:
      - backend
    ports:
      - "6382:6379"
    privileged: true

  redis4:
    image: redis
    networks:
      - backend
    ports:
      - "6383:6379"
    privileged: true
