version: "3.7"
services:
  php56:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:5.6
    networks:
      - backend
    expose:
      - "9000"
    env_file:
      - ./.env
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP56_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true

  php73:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:7.3
    networks:
      - backend
    expose:
      - "9000"
    env_file:
      - ./.env
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP73_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true

  php74:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:7.4
    networks:
      - backend
    expose:
      - "9000"
    env_file:
      - ./.env
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP74_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true

  phpsw73:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:7.3-swoole
    networks:
      - backend
    expose:
      - "9000"
    env_file:
      - ./.env
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP73_SWOOLE_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true

  phpsw74:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:7.4-swoole
    networks:
      - backend
    expose:
      - "9000"
    ports:
      - "9501:9501/tcp"
      - "9502:9502/udp"
      - "9503:9503/tcp"
      - "9504:9504/tcp"
    env_file:
      - ./.env
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP74_SWOOLE_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true
