version: "3.7"
services:
  phpx7:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php7-fpm-xdebug
    networks:
      - backend
    expose:
      - 9000
    ports:
      - 9001-9010:9001-9010
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP7_XDEBUG_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true

  phpsw7:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php7-fpm-swoole
    networks:
      - backend
    expose:
      - 9000
    ports:
      - 9011-9020:9011-9020
      - 9501:9501
      - 9502:9502/udp
      - 9503-9504:9503-9504
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP7_SWOOLE_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true

  phpx8:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php8-fpm-xdebug
    networks:
      - backend
    expose:
      - 9000
    ports:
      - 9021-9030:9021-9030
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP8_XDEBUG_INI_FILE:/usr/local/etc/php/php.ini:ro
    extra_hosts:
      - trink.test:$LOCAL_IP_ADDR
    privileged: true
#    stdin_open: true
#    tty: true
