version: "3.7"
services:
  nginx:
    image: nginx
    networks:
      - backend
    ports:
      - "80:80"
    depends_on:
      - php56
      - php73
      - php74
    env_file:
      - ./.env
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $NGINX_CONFIG_DIR:/etc/nginx/conf.d
      - $NGINX_LOG_DIR:/var/log/nginx
    privileged: true

  php56:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php56
    networks:
      - backend
    expose:
      - "9000"
    env_file:
      - ./.env
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP56_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true
  php73:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php73
    networks:
      - backend
    expose:
      - "9000"
    env_file:
      - ./.env
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP73_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true
  php74:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php74
    networks:
      - backend
    expose:
      - "9000"
    env_file:
      - ./.env
    volumes:
      - $PROJECT_DIR:/var/www/html:rw
      - $PHP74_INI_FILE:/usr/local/etc/php/php.ini:ro
    privileged: true

  mysql:
    image: mysql
    networks:
      - backend
    environment:
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - $MYSQL_DATA_DIR:/var/lib/mysql:rw
      - $MYSQL_CONFIG_FILE:/etc/mysql/my.cnf
    privileged: true
  mongo:
    image: mongo
    networks:
      - backend
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - $MONGO_DATA_DIR:/data/:rw
    privileged: true

  redis:
    image: redis
    networks:
      - backend
    ports:
      - "6379:6379"
    command: redis-server /etc/redis/redis.conf
    env_file:
      - ./.env
    volumes:
      - $REDIS_CONFIG_FILE:/etc/redis/redis.conf:rw
      - $REDIS_DATA_DIR:/data:rw
    privileged: true
  memcached:
    image: memcached
    networks:
      - backend
    ports:
      - "11211:11211"
    env_file:
      - ./.env
    privileged: true

  rabbitmq:
    image: rabbitmq:management
    networks:
      - backend
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASSWORD
    privileged: true
networks:
  backend:
