version: "3.7"
services:
  gateway:
    image: nginx:alpine
    networks:
      - backend
    ports:
      - "80:80"
    depends_on:
      - nginx_1
      - nginx_2
      - nginx_3
    volumes:
      - ./server/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx/gateway:/var/log/nginx
    privileged: true

  nginx_1:
    image: nginx:alpine
    networks:
      - backend
    depends_on:
      - php56_1
      - php73_1
      - php74_1
    volumes:
      - ./server/server1/html:/var/www/html
      - ./server/server1/nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx/server1:/var/log/nginx
    privileged: true
  php56_1:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php56
    networks:
      - backend
    volumes:
      - ./server/server1/html:/var/www/html:rw
      - ./server/server1/php56/php.ini:/usr/local/etc/php/php.ini:ro
    privileged: true
  php73_1:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php73
    networks:
      - backend
    volumes:
      - ./server/server1/html:/var/www/html:rw
      - ./server/server1/php73/php.ini:/usr/local/etc/php/php.ini:ro
    privileged: true
  php74_1:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php74
    networks:
      - backend
    volumes:
      - ./server/server1/html:/var/www/html:rw
      - ./server/server1/php74/php.ini:/usr/local/etc/php/php.ini:ro
    privileged: true

  nginx_2:
    image: nginx:alpine
    networks:
      - backend
    depends_on:
      - php56_2
      - php73_2
      - php74_2
    volumes:
      - ./server/server2/html:/var/www/html
      - ./server/server2/nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx/server2:/var/log/nginx
    privileged: true
  php56_2:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php56
    networks:
      - backend
    volumes:
      - ./server/server2/html:/var/www/html:rw
      - ./server/server2/php56/php.ini:/usr/local/etc/php/php.ini:ro
    privileged: true
  php73_2:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php73
    networks:
      - backend
    volumes:
      - ./server/server2/html:/var/www/html:rw
      - ./server/server2/php73/php.ini:/usr/local/etc/php/php.ini:ro
    privileged: true
  php74_2:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php74
    networks:
      - backend
    volumes:
      - ./server/server2/html:/var/www/html:rw
      - ./server/server2/php74/php.ini:/usr/local/etc/php/php.ini:ro
    privileged: true

  nginx_3:
    image: nginx:alpine
    networks:
      - backend
    depends_on:
      - php56_3
      - php73_3
      - php74_3
    volumes:
      - ./server/server3/html:/var/www/html
      - ./server/server3/nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx/server3:/var/log/nginx
    privileged: true
  php56_3:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php56
    networks:
      - backend
    volumes:
      - ./server/server3/html:/var/www/html:rw
      - ./server/server3/php56/php.ini:/usr/local/etc/php/php.ini:ro
    privileged: true
  php73_3:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php73
    networks:
      - backend
    volumes:
      - ./server/server3/html:/var/www/html:rw
      - ./server/server3/php73/php.ini:/usr/local/etc/php/php.ini:ro
    privileged: true
  php74_3:
    image: registry.cn-hangzhou.aliyuncs.com/treelink/php:php74
    networks:
      - backend
    volumes:
      - ./server/server3/html:/var/www/html:rw
      - ./server/server3/php74/php.ini:/usr/local/etc/php/php.ini:ro
    privileged: true
networks:
  backend: