version: "3.7"
services:
  nginx:
    image: nginx:alpine
    networks:
      - backend
    ports:
      - "80:80"
    depends_on:
      - php_fpm
    volumes:
      - ./html:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    privileged: true
  php_fpm:
    build: ./php/
    networks:
      - backend
    expose:
      - "9000"
    volumes:
      - ./html:/var/www/html:rw
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./logs/php-fpm:/var/log/php-fpm:rw
    command: php-fpm
    privileged: true
  mysql:
    image: mysql
    networks:
      - backend
    environment:
        MYSQL_ROOT_PASSWORD: "123123"
    ports:
      - "3333:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
    privileged: true
  mongo:
    image: mongo
    networks:
      - backend
    ports:
      - "57017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123123
    volumes:
      - ./mongo/data:/data/:rw
    privileged: true
  redis:
    image: redis:alpine
    networks:
      - backend
    ports:
      - "6379:6379"
    privileged: true
networks:
  backend:
