# docker inspect containerID
CREATE USER 'slave'@'172.63.1.3' IDENTIFIED BY '123123';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'slave'@'172.63.1.3';
FLUSH PRIVILEGES;
SHOW MASTER STATUS;
